# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reaplylens

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_06122a07943e4962aca5481b22a911ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_02ab0f5d4e414e2398be6512e073df5f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_06122a07943e4962aca5481b22a911ca }}/vusim07/reaplylens:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reaplylens'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dfa86ec4676e4a7dbd6c0533d05c0032 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_06122a07943e4962aca5481b22a911ca }}/vusim07/reaplylens:${{ github.sha }}'